// Initial Seed Data for Multi-Site Enterprise VMS

export const initialSites = [
  { id: 'site-home', name: 'Home CP PLUS DVR (8 Channels)', city: 'Home', code: 'CPP-01', totalCameras: 8 },
  { id: 'site-1', name: 'Mumbai Manufacturing Plant', city: 'Mumbai', code: 'BOM-01', totalCameras: 4 },
  { id: 'site-2', name: 'Delhi Head Office', city: 'New Delhi', code: 'DEL-01', totalCameras: 2 },
  { id: 'site-3', name: 'Bangalore Logistics Hub', city: 'Bengaluru', code: 'BLR-01', totalCameras: 2 },
];

export const initialCameras = [
  {
    id: 'cpplus-1',
    siteId: 'site-home',
    name: 'CP PLUS Cam 01 (Channel 1)',
    location: 'Channel 01',
    sceneType: 'real',
    ip: '192.168.1.2',
    rtspUrl: 'rtsp://admin:kumar@1212@192.168.1.2:554/cam/realmonitor?channel=1&subtype=0',
    liveStreamUrl: 'http://localhost:8889/cpplus_ch1/',
    onvifPort: 554,
    resolution: '1920x1080 (HD)',
    fps: 25,
    bitrate: '4096 kbps',
    codec: 'H.265 Main',
    status: 'online',
    ptzCapable: false,
    twoWayAudioCapable: true,
    temperatureC: 38,
    latencyMs: 1,
    packetLossPercent: 0.00,
    uptimeDays: 65,
    isRecording: true,
    hasAiAnalytics: true,
    pan: 0,
    tilt: 0,
    zoom: 1.0,
  },
  {
    id: 'cpplus-2',
    siteId: 'site-home',
    name: 'CP PLUS Cam 02 (Channel 2)',
    location: 'Channel 02',
    sceneType: 'real',
    ip: '192.168.1.2',
    rtspUrl: 'rtsp://admin:kumar@1212@192.168.1.2:554/cam/realmonitor?channel=2&subtype=0',
    liveStreamUrl: 'http://localhost:8889/cpplus_ch2/',
    onvifPort: 554,
    resolution: '1920x1080 (HD)',
    fps: 25,
    bitrate: '4096 kbps',
    codec: 'H.265 Main',
    status: 'online',
    ptzCapable: false,
    twoWayAudioCapable: true,
    temperatureC: 38,
    latencyMs: 1,
    packetLossPercent: 0.00,
    uptimeDays: 65,
    isRecording: true,
    hasAiAnalytics: true,
    pan: 0,
    tilt: 0,
    zoom: 1.0,
  },
  {
    id: 'cpplus-3',
    siteId: 'site-home',
    name: 'CP PLUS Cam 03 (Channel 3)',
    location: 'Channel 03',
    sceneType: 'real',
    ip: '192.168.1.2',
    rtspUrl: 'rtsp://admin:kumar@1212@192.168.1.2:554/cam/realmonitor?channel=3&subtype=0',
    liveStreamUrl: 'http://localhost:8889/cpplus_ch3/',
    onvifPort: 554,
    resolution: '1920x1080 (HD)',
    fps: 25,
    bitrate: '4096 kbps',
    codec: 'H.265 Main',
    status: 'online',
    ptzCapable: false,
    twoWayAudioCapable: true,
    temperatureC: 38,
    latencyMs: 1,
    packetLossPercent: 0.00,
    uptimeDays: 65,
    isRecording: true,
    hasAiAnalytics: true,
    pan: 0,
    tilt: 0,
    zoom: 1.0,
  },
  {
    id: 'cpplus-4',
    siteId: 'site-home',
    name: 'CP PLUS Cam 04 (Channel 4)',
    location: 'Channel 04',
    sceneType: 'real',
    ip: '192.168.1.2',
    rtspUrl: 'rtsp://admin:kumar@1212@192.168.1.2:554/cam/realmonitor?channel=4&subtype=0',
    liveStreamUrl: 'http://localhost:8889/cpplus_ch4/',
    onvifPort: 554,
    resolution: '1920x1080 (HD)',
    fps: 25,
    bitrate: '4096 kbps',
    codec: 'H.265 Main',
    status: 'online',
    ptzCapable: false,
    twoWayAudioCapable: true,
    temperatureC: 38,
    latencyMs: 1,
    packetLossPercent: 0.00,
    uptimeDays: 65,
    isRecording: true,
    hasAiAnalytics: true,
    pan: 0,
    tilt: 0,
    zoom: 1.0,
  },
  {
    id: 'cpplus-5',
    siteId: 'site-home',
    name: 'CP PLUS Cam 05 (Channel 5)',
    location: 'Channel 05',
    sceneType: 'real',
    ip: '192.168.1.2',
    rtspUrl: 'rtsp://admin:kumar@1212@192.168.1.2:554/cam/realmonitor?channel=5&subtype=0',
    liveStreamUrl: 'http://localhost:8889/cpplus_ch5/',
    onvifPort: 554,
    resolution: '1920x1080 (HD)',
    fps: 25,
    bitrate: '4096 kbps',
    codec: 'H.265 Main',
    status: 'online',
    ptzCapable: false,
    twoWayAudioCapable: true,
    temperatureC: 38,
    latencyMs: 1,
    packetLossPercent: 0.00,
    uptimeDays: 65,
    isRecording: true,
    hasAiAnalytics: true,
    pan: 0,
    tilt: 0,
    zoom: 1.0,
  },
  {
    id: 'cpplus-6',
    siteId: 'site-home',
    name: 'CP PLUS Cam 06 (Channel 6)',
    location: 'Channel 06',
    sceneType: 'real',
    ip: '192.168.1.2',
    rtspUrl: 'rtsp://admin:kumar@1212@192.168.1.2:554/cam/realmonitor?channel=6&subtype=0',
    liveStreamUrl: 'http://localhost:8889/cpplus_ch6/',
    onvifPort: 554,
    resolution: '1920x1080 (HD)',
    fps: 25,
    bitrate: '4096 kbps',
    codec: 'H.265 Main',
    status: 'online',
    ptzCapable: false,
    twoWayAudioCapable: true,
    temperatureC: 38,
    latencyMs: 1,
    packetLossPercent: 0.00,
    uptimeDays: 65,
    isRecording: true,
    hasAiAnalytics: true,
    pan: 0,
    tilt: 0,
    zoom: 1.0,
  },
  {
    id: 'cpplus-7',
    siteId: 'site-home',
    name: 'CP PLUS Cam 07 (Channel 7)',
    location: 'Channel 07',
    sceneType: 'real',
    ip: '192.168.1.2',
    rtspUrl: 'rtsp://admin:kumar@1212@192.168.1.2:554/cam/realmonitor?channel=7&subtype=0',
    liveStreamUrl: 'http://localhost:8889/cpplus_ch7/',
    onvifPort: 554,
    resolution: '1920x1080 (HD)',
    fps: 25,
    bitrate: '4096 kbps',
    codec: 'H.265 Main',
    status: 'online',
    ptzCapable: false,
    twoWayAudioCapable: true,
    temperatureC: 38,
    latencyMs: 1,
    packetLossPercent: 0.00,
    uptimeDays: 65,
    isRecording: true,
    hasAiAnalytics: true,
    pan: 0,
    tilt: 0,
    zoom: 1.0,
  },
  {
    id: 'cpplus-8',
    siteId: 'site-home',
    name: 'CP PLUS Cam 08 (Channel 8)',
    location: 'Channel 08',
    sceneType: 'real',
    ip: '192.168.1.2',
    rtspUrl: 'rtsp://admin:kumar@1212@192.168.1.2:554/cam/realmonitor?channel=8&subtype=0',
    liveStreamUrl: 'http://localhost:8889/cpplus_ch8/',
    onvifPort: 554,
    resolution: '1920x1080 (HD)',
    fps: 25,
    bitrate: '4096 kbps',
    codec: 'H.265 Main',
    status: 'online',
    ptzCapable: false,
    twoWayAudioCapable: true,
    temperatureC: 38,
    latencyMs: 1,
    packetLossPercent: 0.00,
    uptimeDays: 65,
    isRecording: true,
    hasAiAnalytics: true,
    pan: 0,
    tilt: 0,
    zoom: 1.0,
  },
  {
    id: 'cam-1',
    siteId: 'site-1',
    name: 'Main Gate PTZ - Entry',
    location: 'Gate 01 North',
    sceneType: 'gate',
    ip: '192.168.1.101',
    rtspUrl: 'rtsp://admin:AegisSec2026@192.168.1.101:554/live/ch0',
    onvifPort: 80,
    resolution: '3840x2160 (4K)',
    fps: 30,
    bitrate: '4096 kbps',
    codec: 'H.265 Main',
    status: 'online',
    ptzCapable: true,
    twoWayAudioCapable: true,
    temperatureC: 41,
    latencyMs: 14,
    packetLossPercent: 0.01,
    uptimeDays: 28,
    isRecording: true,
    hasAiAnalytics: true,
    pan: 0,
    tilt: 0,
    zoom: 1.0,
  },
  {
    id: 'cam-2',
    siteId: 'site-1',
    name: 'Loading Dock & Bay 03',
    location: 'Warehouse Dock A',
    sceneType: 'warehouse',
    ip: '192.168.1.102',
    rtspUrl: 'rtsp://admin:AegisSec2026@192.168.1.102:554/live/ch0',
    onvifPort: 80,
    resolution: '1920x1080 (FHD)',
    fps: 25,
    bitrate: '2048 kbps',
    codec: 'H.264 High',
    status: 'online',
    ptzCapable: false,
    twoWayAudioCapable: true,
    temperatureC: 39,
    latencyMs: 18,
    packetLossPercent: 0.02,
    uptimeDays: 14,
    isRecording: true,
    hasAiAnalytics: true,
    pan: 0,
    tilt: 0,
    zoom: 1.0,
  },
  {
    id: 'cam-3',
    siteId: 'site-1',
    name: 'Perimeter Wall East (Thermal)',
    location: 'Boundary Fence East',
    sceneType: 'perimeter',
    ip: '192.168.1.103',
    rtspUrl: 'rtsp://admin:AegisSec2026@192.168.1.103:554/live/ch0',
    onvifPort: 8000,
    resolution: '1920x1080 (FHD)',
    fps: 20,
    bitrate: '1536 kbps',
    codec: 'H.265',
    status: 'online',
    ptzCapable: true,
    twoWayAudioCapable: false,
    temperatureC: 44,
    latencyMs: 22,
    packetLossPercent: 0.04,
    uptimeDays: 45,
    isRecording: true,
    hasAiAnalytics: true,
    pan: 0,
    tilt: 0,
    zoom: 1.0,
  },
  {
    id: 'cam-4',
    siteId: 'site-1',
    name: 'Machine Assembly Floor',
    location: 'Production Line 02',
    sceneType: 'assembly',
    ip: '192.168.1.104',
    rtspUrl: 'rtsp://admin:AegisSec2026@192.168.1.104:554/live/ch0',
    onvifPort: 80,
    resolution: '2560x1440 (2K)',
    fps: 25,
    bitrate: '2560 kbps',
    codec: 'H.264',
    status: 'online',
    ptzCapable: false,
    twoWayAudioCapable: false,
    temperatureC: 40,
    latencyMs: 15,
    packetLossPercent: 0.01,
    uptimeDays: 30,
    isRecording: true,
    hasAiAnalytics: false,
    pan: 0,
    tilt: 0,
    zoom: 1.0,
  },
  {
    id: 'cam-5',
    siteId: 'site-2',
    name: 'Reception & Visitor Access',
    location: 'Ground Floor Lobby',
    sceneType: 'office',
    ip: '192.168.2.110',
    rtspUrl: 'rtsp://admin:AegisSec2026@192.168.2.110:554/live/ch0',
    onvifPort: 80,
    resolution: '1920x1080 (FHD)',
    fps: 25,
    bitrate: '2048 kbps',
    codec: 'H.265',
    status: 'online',
    ptzCapable: false,
    twoWayAudioCapable: true,
    temperatureC: 38,
    latencyMs: 12,
    packetLossPercent: 0.00,
    uptimeDays: 60,
    isRecording: true,
    hasAiAnalytics: true,
    pan: 0,
    tilt: 0,
    zoom: 1.0,
  },
  {
    id: 'cam-6',
    siteId: 'site-2',
    name: 'Data Center Server Vault',
    location: 'Basement Tech Room',
    sceneType: 'server',
    ip: '192.168.2.115',
    rtspUrl: 'rtsp://admin:AegisSec2026@192.168.2.115:554/live/ch0',
    onvifPort: 80,
    resolution: '1920x1080 (FHD)',
    fps: 30,
    bitrate: '2048 kbps',
    codec: 'H.264',
    status: 'online',
    ptzCapable: true,
    twoWayAudioCapable: false,
    temperatureC: 35,
    latencyMs: 8,
    packetLossPercent: 0.00,
    uptimeDays: 92,
    isRecording: true,
    hasAiAnalytics: true,
    pan: 0,
    tilt: 0,
    zoom: 1.0,
  },
  {
    id: 'cam-7',
    siteId: 'site-3',
    name: 'Container Parking & ANPR',
    location: 'Truck Gate Terminal',
    sceneType: 'parking',
    ip: '192.168.3.120',
    rtspUrl: 'rtsp://admin:AegisSec2026@192.168.3.120:554/live/ch0',
    onvifPort: 80,
    resolution: '3840x2160 (4K)',
    fps: 30,
    bitrate: '4096 kbps',
    codec: 'H.265',
    status: 'online',
    ptzCapable: true,
    twoWayAudioCapable: true,
    temperatureC: 43,
    latencyMs: 25,
    packetLossPercent: 0.03,
    uptimeDays: 19,
    isRecording: true,
    hasAiAnalytics: true,
    pan: 0,
    tilt: 0,
    zoom: 1.0,
  },
  {
    id: 'cam-8',
    siteId: 'site-3',
    name: 'High-Value Vault Zone',
    location: 'Secure Area 04',
    sceneType: 'vault',
    ip: '192.168.3.125',
    rtspUrl: 'rtsp://admin:AegisSec2026@192.168.3.125:554/live/ch0',
    onvifPort: 80,
    resolution: '1920x1080 (FHD)',
    fps: 20,
    bitrate: '1536 kbps',
    codec: 'H.265',
    status: 'online',
    ptzCapable: false,
    twoWayAudioCapable: true,
    temperatureC: 36,
    latencyMs: 14,
    packetLossPercent: 0.01,
    uptimeDays: 33,
    isRecording: true,
    hasAiAnalytics: true,
    pan: 0,
    tilt: 0,
    zoom: 1.0,
  },
];

export const initialTripwires = [
  {
    id: 'tw-1',
    cameraId: 'cam-1',
    name: 'Gate 01 Vehicle Inbound Line',
    type: 'line',
    points: [{ x: 0.15, y: 0.7 }, { x: 0.85, y: 0.7 }],
    direction: 'A_TO_B',
    targetClasses: ['person', 'vehicle'],
    sensitivity: 85,
    enabled: true,
    color: '#ef4444',
  },
  {
    id: 'tw-2',
    cameraId: 'cam-3',
    name: 'East Perimeter Anti-Climb Fence',
    type: 'line',
    points: [{ x: 0.1, y: 0.45 }, { x: 0.9, y: 0.45 }],
    direction: 'BOTH',
    targetClasses: ['person'],
    sensitivity: 90,
    enabled: true,
    color: '#f59e0b',
  },
];

export const initialCloudflareConfig = {
  accountId: 'cf_sec_89f029a8c14d9b',
  bucketName: 'aegis-vms-prod-recordings',
  endpoint: 'https://cf_sec_89f029a8c14d9b.r2.cloudflarestorage.com',
  accessKeyId: '9840294bdf34091a82',
  secretAccessKey: '••••••••••••••••••••••••••••••••',
  zeroTrustTunnelId: 'tunnel-mumbai-delhi-prod-01',
  tunnelStatus: 'healthy',
  retentionDays: 30,
  usedStorageTB: 1.34,
  quotaStorageTB: 5.0,
  monthlyCostUSD: 20.10,
  egressCostUSD: 0.00,
};

export const initialUsers = [
  { id: 'usr-1', name: 'Vikram Malhotra', email: 'admin@aegis-vms.io', role: 'Super Admin', sites: ['All Sites'] },
  { id: 'usr-2', name: 'Pooja Sharma', email: 'pooja.mumbai@aegis-vms.io', role: 'Branch Manager', sites: ['Mumbai Manufacturing Plant'] },
  { id: 'usr-3', name: 'Rajesh Kumar', email: 'guard.station01@aegis-vms.io', role: 'Security Guard', sites: ['Mumbai Manufacturing Plant'] },
  { id: 'usr-4', name: 'Ananya Verma', email: 'compliance@aegis-vms.io', role: 'Auditor', sites: ['All Sites'] },
];

export const initialEvents = [
  {
    id: 'ev-1',
    cameraId: 'cam-1',
    cameraName: 'Main Gate PTZ - Entry',
    siteName: 'Mumbai Plant',
    type: 'Line Crossing',
    target: 'Commercial Vehicle (Truck)',
    confidence: '94%',
    timestamp: '16:45:12',
    severity: 'high',
    thumbnail: 'vehicle_gate',
    acknowledged: false,
  },
  {
    id: 'ev-2',
    cameraId: 'cam-3',
    cameraName: 'Perimeter Wall East (Thermal)',
    siteName: 'Mumbai Plant',
    type: 'Intrusion Detection',
    target: 'Person (Boundary Breach)',
    confidence: '89%',
    timestamp: '16:48:30',
    severity: 'critical',
    thumbnail: 'person_fence',
    acknowledged: false,
  },
  {
    id: 'ev-3',
    cameraId: 'cam-7',
    cameraName: 'Container Parking & ANPR',
    siteName: 'Bangalore Logistics',
    type: 'Vehicle Plate Recognition',
    target: 'MH-04-AZ-4921',
    confidence: '98%',
    timestamp: '16:51:04',
    severity: 'info',
    thumbnail: 'plate_scan',
    acknowledged: true,
  },
];

// Indexed AI Forensic Events for Smart Attribute Search
export const initialForensicRecords = [
  {
    id: 'fn-1',
    cameraId: 'cam-1',
    cameraName: 'Main Gate PTZ - Entry',
    targetType: 'vehicle',
    color: 'White',
    licensePlate: 'MH-04-AZ-4921',
    time: '14:23:10',
    date: '2026-10-03',
    confidence: '96%',
    description: 'White Logistics Delivery Truck entered Gate 01',
  },
  {
    id: 'fn-2',
    cameraId: 'cam-5',
    cameraName: 'Reception & Visitor Access',
    targetType: 'person',
    color: 'Blue',
    licensePlate: 'N/A',
    time: '14:35:44',
    date: '2026-10-03',
    confidence: '94%',
    description: 'Person wearing Blue Jacket checked in at reception',
  },
  {
    id: 'fn-3',
    cameraId: 'cam-7',
    cameraName: 'Container Parking & ANPR',
    targetType: 'vehicle',
    color: 'Black',
    licensePlate: 'DL-01-CQ-8822',
    time: '15:10:02',
    date: '2026-10-03',
    confidence: '98%',
    description: 'Black Sedan parked in Bay 4',
  },
  {
    id: 'fn-4',
    cameraId: 'cam-3',
    cameraName: 'Perimeter Wall East (Thermal)',
    targetType: 'person',
    color: 'Red',
    licensePlate: 'N/A',
    time: '15:42:19',
    date: '2026-10-03',
    confidence: '91%',
    description: 'Person wearing Red Hood loitered near East perimeter fence',
  },
  {
    id: 'fn-5',
    cameraId: 'cam-2',
    cameraName: 'Loading Dock & Bay 03',
    targetType: 'vehicle',
    color: 'Yellow',
    licensePlate: 'KA-05-MM-1029',
    time: '16:04:55',
    date: '2026-10-03',
    confidence: '92%',
    description: 'Yellow Forklift vehicle operating at Dock A',
  },
];
