// Initial Seed Data for Multi-Site Enterprise VMS

export const initialSites = [
  { id: 'site-home', name: 'Home CP PLUS DVR (8 Channels)', city: 'Home', code: 'CPP-01', totalCameras: 8 },
];

export const initialCameras = [
  {
    id: 'cpplus-1',
    siteId: 'site-home',
    name: 'CP PLUS Cam 01 (Channel 1)',
    location: 'Channel 01',
    sceneType: 'real',
    ip: '192.168.1.2',
    rtspUrl: 'rtsp://admin:kumar@1212@192.168.1.2:554/cam/realmonitor?channel=1&subtype=0',
    liveStreamUrl: 'http://localhost:8888/cpplus_ch1/?autoplay=true&muted=true&controls=false',
    onvifPort: 554,
    resolution: '1920x1080 (HD)',
    fps: 25,
    bitrate: '4096 kbps',
    codec: 'H.265 Main',
    status: 'online',
    ptzCapable: false,
    twoWayAudioCapable: true,
    temperatureC: 38,
    latencyMs: 1,
    packetLossPercent: 0.00,
    uptimeDays: 65,
    isRecording: true,
    hasAiAnalytics: true,
    pan: 0,
    tilt: 0,
    zoom: 1.0,
  },
  {
    id: 'cpplus-2',
    siteId: 'site-home',
    name: 'CP PLUS Cam 02 (Channel 2)',
    location: 'Channel 02',
    sceneType: 'real',
    ip: '192.168.1.2',
    rtspUrl: 'rtsp://admin:kumar@1212@192.168.1.2:554/cam/realmonitor?channel=2&subtype=0',
    liveStreamUrl: 'http://localhost:8888/cpplus_ch2/?autoplay=true&muted=true&controls=false',
    onvifPort: 554,
    resolution: '1920x1080 (HD)',
    fps: 25,
    bitrate: '4096 kbps',
    codec: 'H.265 Main',
    status: 'online',
    ptzCapable: false,
    twoWayAudioCapable: true,
    temperatureC: 38,
    latencyMs: 1,
    packetLossPercent: 0.00,
    uptimeDays: 65,
    isRecording: true,
    hasAiAnalytics: true,
    pan: 0,
    tilt: 0,
    zoom: 1.0,
  },
  {
    id: 'cpplus-3',
    siteId: 'site-home',
    name: 'CP PLUS Cam 03 (Channel 3)',
    location: 'Channel 03',
    sceneType: 'real',
    ip: '192.168.1.2',
    rtspUrl: 'rtsp://admin:kumar@1212@192.168.1.2:554/cam/realmonitor?channel=3&subtype=0',
    liveStreamUrl: 'http://localhost:8888/cpplus_ch3/?autoplay=true&muted=true&controls=false',
    onvifPort: 554,
    resolution: '1920x1080 (HD)',
    fps: 25,
    bitrate: '4096 kbps',
    codec: 'H.265 Main',
    status: 'online',
    ptzCapable: false,
    twoWayAudioCapable: true,
    temperatureC: 38,
    latencyMs: 1,
    packetLossPercent: 0.00,
    uptimeDays: 65,
    isRecording: true,
    hasAiAnalytics: true,
    pan: 0,
    tilt: 0,
    zoom: 1.0,
  },
  {
    id: 'cpplus-4',
    siteId: 'site-home',
    name: 'CP PLUS Cam 04 (Channel 4)',
    location: 'Channel 04',
    sceneType: 'real',
    ip: '192.168.1.2',
    rtspUrl: 'rtsp://admin:kumar@1212@192.168.1.2:554/cam/realmonitor?channel=4&subtype=0',
    liveStreamUrl: 'http://localhost:8888/cpplus_ch4/?autoplay=true&muted=true&controls=false',
    onvifPort: 554,
    resolution: '1920x1080 (HD)',
    fps: 25,
    bitrate: '4096 kbps',
    codec: 'H.265 Main',
    status: 'online',
    ptzCapable: false,
    twoWayAudioCapable: true,
    temperatureC: 38,
    latencyMs: 1,
    packetLossPercent: 0.00,
    uptimeDays: 65,
    isRecording: true,
    hasAiAnalytics: true,
    pan: 0,
    tilt: 0,
    zoom: 1.0,
  },
  {
    id: 'cpplus-5',
    siteId: 'site-home',
    name: 'CP PLUS Cam 05 (Channel 5)',
    location: 'Channel 05',
    sceneType: 'real',
    ip: '192.168.1.2',
    rtspUrl: 'rtsp://admin:kumar@1212@192.168.1.2:554/cam/realmonitor?channel=5&subtype=0',
    liveStreamUrl: 'http://localhost:8888/cpplus_ch5/?autoplay=true&muted=true&controls=false',
    onvifPort: 554,
    resolution: '1920x1080 (HD)',
    fps: 25,
    bitrate: '4096 kbps',
    codec: 'H.265 Main',
    status: 'online',
    ptzCapable: false,
    twoWayAudioCapable: true,
    temperatureC: 38,
    latencyMs: 1,
    packetLossPercent: 0.00,
    uptimeDays: 65,
    isRecording: true,
    hasAiAnalytics: true,
    pan: 0,
    tilt: 0,
    zoom: 1.0,
  },
  {
    id: 'cpplus-6',
    siteId: 'site-home',
    name: 'CP PLUS Cam 06 (Channel 6)',
    location: 'Channel 06',
    sceneType: 'real',
    ip: '192.168.1.2',
    rtspUrl: 'rtsp://admin:kumar@1212@192.168.1.2:554/cam/realmonitor?channel=6&subtype=0',
    liveStreamUrl: 'http://localhost:8888/cpplus_ch6/?autoplay=true&muted=true&controls=false',
    onvifPort: 554,
    resolution: '1920x1080 (HD)',
    fps: 25,
    bitrate: '4096 kbps',
    codec: 'H.265 Main',
    status: 'online',
    ptzCapable: false,
    twoWayAudioCapable: true,
    temperatureC: 38,
    latencyMs: 1,
    packetLossPercent: 0.00,
    uptimeDays: 65,
    isRecording: true,
    hasAiAnalytics: true,
    pan: 0,
    tilt: 0,
    zoom: 1.0,
  },
  {
    id: 'cpplus-7',
    siteId: 'site-home',
    name: 'CP PLUS Cam 07 (Channel 7)',
    location: 'Channel 07',
    sceneType: 'real',
    ip: '192.168.1.2',
    rtspUrl: 'rtsp://admin:kumar@1212@192.168.1.2:554/cam/realmonitor?channel=7&subtype=0',
    liveStreamUrl: 'http://localhost:8888/cpplus_ch7/?autoplay=true&muted=true&controls=false',
    onvifPort: 554,
    resolution: '1920x1080 (HD)',
    fps: 25,
    bitrate: '4096 kbps',
    codec: 'H.265 Main',
    status: 'online',
    ptzCapable: false,
    twoWayAudioCapable: true,
    temperatureC: 38,
    latencyMs: 1,
    packetLossPercent: 0.00,
    uptimeDays: 65,
    isRecording: true,
    hasAiAnalytics: true,
    pan: 0,
    tilt: 0,
    zoom: 1.0,
  },
  {
    id: 'cpplus-8',
    siteId: 'site-home',
    name: 'CP PLUS Cam 08 (Channel 8)',
    location: 'Channel 08',
    sceneType: 'real',
    ip: '192.168.1.2',
    rtspUrl: 'rtsp://admin:kumar@1212@192.168.1.2:554/cam/realmonitor?channel=8&subtype=0',
    liveStreamUrl: 'http://localhost:8888/cpplus_ch8/?autoplay=true&muted=true&controls=false',
    onvifPort: 554,
    resolution: '1920x1080 (HD)',
    fps: 25,
    bitrate: '4096 kbps',
    codec: 'H.265 Main',
    status: 'online',
    ptzCapable: false,
    twoWayAudioCapable: true,
    temperatureC: 38,
    latencyMs: 1,
    packetLossPercent: 0.00,
    uptimeDays: 65,
    isRecording: true,
    hasAiAnalytics: true,
    pan: 0,
    tilt: 0,
    zoom: 1.0,
  },
];

export const initialTripwires = [
  {
    id: 'tw-1',
    cameraId: 'cpplus-1',
    name: 'Front Gate Boundary Tripwire',
    type: 'line',
    points: [{ x: 0.15, y: 0.7 }, { x: 0.85, y: 0.7 }],
    direction: 'A_TO_B',
    targetClasses: ['person', 'vehicle'],
    sensitivity: 85,
    enabled: false,
    color: '#ef4444',
  },
];

export const initialCloudflareConfig = {
  accountId: 'cf_sec_89f029a8c14d9b',
  bucketName: 'aegis-vms-prod-recordings',
  endpoint: 'https://cf_sec_89f029a8c14d9b.r2.cloudflarestorage.com',
  accessKeyId: '9840294bdf34091a82',
  secretAccessKey: '••••••••••••••••••••••••••••••••',
  zeroTrustTunnelId: 'tunnel-home-cpplus-prod-01',
  tunnelStatus: 'healthy',
  retentionDays: 30,
  usedStorageTB: 1.34,
  quotaStorageTB: 5.0,
  monthlyCostUSD: 20.10,
  egressCostUSD: 0.00,
};

export const initialUsers = [
  { id: 'usr-1', name: 'System Administrator', email: 'admin@aegis-vms.io', role: 'Super Admin', sites: ['All Sites'] },
];

export const initialEvents = [];

// Indexed AI Forensic Events for Smart Attribute Search
export const initialForensicRecords = [];
